### ISSUE TITLE
cfgtest.py:90 format 키 없는 오류

### ISSUE THREAD

**Issue by keedongpark** [haje01/wdfwd#2]
정규식 format 지정이 파일 단위로 지정하지 않는 것이 기본 예시로 되어 있는데 
cfgtest.py에서는 확인 없이 바로 "format"을 키로 파일 항목에서 찾게 되어 있습니다. 

cfgtest에서도 tailing에 지정된 format을 파일 단위에 지정 안 된 경우 쓰도록 해야 할 것 같습니다. 

감사합니다.

**Comment by haje01** [comment]
3cb7aea68219757fa474d66e0cf629e780334e4f 로 수정하고 빌드 올렸습니다. 가능하시면 https://github.com/haje01/wdfwd/releases/tag/v0.1.3 받으셔서 테스트 부탁드리겠습니다.
